version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    networks:
      - fastapi-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgresql@db:5432/fastapi_db
    networks:
      - fastapi-network
networks:
  fastapi-network:
    driver: bridge
