apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movieapp-ingress
  namespace: movieapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: movieapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: movieapp-service
                port:
                  number: 80