apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: movieapp
type: Opaque
data:
  POSTGRESS_USER: cG9zdGdyZXM=
  POSTGRESS_PASSWORD: cG9zdGdyZXNxbA==
  POSTGRESS_DB: ZmFzdGFwaV9kYg==